### ISSUE TITLE
How long contents of avatax_responses table are needed?

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-avatax-plugin#9]
The table avatax_responses seems to store a huge lot of rows, and it is by far the largest killbill table by number of rows (10x more than audit_log for example in our setup). Are all the content of this table needed? forever? Is it possible to trim it?

**Comment by pierre** [comment]
This table is needed to perform idempotency checks, to avoid double taxing already taxed items.

In the future, please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Comment by GregOriol** [comment]
I understand about the contribution, but I'm also trying to find out if there is a bug (or a feature request) behind this question.

I'm not sure here, but is it normal to have that many rows in this table? We currently have more than 10x the number of rows in audit_log, and obviously much much more than we have in invoices (~200x). Are you certain that all those entries are needed?

**Comment by pierre** [comment]
> Are you certain that all those entries are needed?

If you delete older entries, idempotency checks won't be performed anymore. This might be fine in your setup if you are guaranteed that invoices won't be reprocessed, this really depends on a lot of factors.

If you still have concerns, let's continue the discussion on the mailing-list and maybe give us more details about why the size matters to you (we know of deployments with **b**illions of rows, and performance isn't a concern).
